In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [3]:
np_array= np.array([1,2,3,4,5])
np_array

array([1, 2, 3, 4, 5])

In [4]:
np.shape(np_array) ## 1 dimensional array

(5,)

In [5]:
two_d_array = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]]) ##2d array


In [6]:
np.shape(two_d_array)

(3, 3)

In [7]:
##matrix same as 2d

matrix = np.array([[2,4,6],
                   [8,10,12]])
matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#### Creating arrays from python list

In [8]:
np.array([1,2,3,4]) ###use when already have a list

array([1, 2, 3, 4])

#### With default values

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

#### Creating sequences of numbers

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### Creating identity matrix

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Operations and Properties of Numpy array

In [14]:
import numpy as np

In [15]:
arr_2d =  np.array([[1,2,3],
                    [4,5,6]])

In [16]:
arr_2d.shape ##structure of array

(2, 3)

In [17]:
arr_2d.size ##number of elements in an array

6

In [18]:
arr_2d.ndim ##dimension of array

2

In [19]:
arr_1d = np.array([1,2,3])
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
arr_3d

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [20]:
arr_3d.shape ##1 block and 4 rows,2 columns

(1, 4, 2)

In [21]:
display(arr_1d.ndim)
display(arr_3d.ndim)

1

3

In [29]:
arr_2d.dtype  ##check data type

dtype('int32')

In [23]:
arr_2d.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
age = np.array(['28','33','25','38'])

In [ ]:
age = age.astype(int) ##change data type of array

In [28]:
age.dtype

dtype('int32')

### Maths operation with numpy

In [30]:
import numpy as np

In [31]:
arr = np.array([10,20,30])

In [32]:
arr+5 ##without loops

array([15, 25, 35])

In [34]:
arr*2 ##without loops

array([20, 40, 60])

In [35]:
arr**2 ##without loops

array([100, 400, 900])

### Aggregation Functions

In [ ]:
## np.sum(array)
##np.mean(array)
##np.min(array)
##np.max(array)
##np.std(array) standard deviation
##np.var(array) variance

In [36]:
a= np.array([[10,20,30],
          [40,50,60],
          [70,80,90]])

In [40]:
np.sum(a) ##simple sum of all elements

450

In [39]:
np.sum(a,axis=0) ## ---> row wise operation downwards, each column gets one value 

array([120, 150, 180])

In [37]:
np.sum(a,axis = 1) ## ----> column wise operation left to right, each row gets one result. 
## For ex: 0 10 + 20 + 30 --> 60

array([ 60, 150, 240])

In [41]:
display(np.mean(a))
display(np.std(a))
display(np.min(a))
display(np.max(a))
display(np.var(a))

50.0

25.81988897471611

10

90

666.6666666666666

### Indexing and Slicing

In [ ]:
'''array[index] #1d array
array[row,column] ##2d '''

In [49]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

In [50]:
arr[0],arr[2],arr[-1]

(10, 30, 60)

In [51]:
arr[1:3]

array([20, 30])

In [53]:
arr[::2]

array([10, 30, 50])

In [52]:
arr[::-1] #reverse order

array([60, 50, 40, 30, 20, 10])

In [ ]:
b= np.array([[10,20,30],
          [40,50,60],
          [70,80,90]])
b[:2,:2] ##array[row index,column index]

array([[10, 20],
       [40, 50]])

### Fancy Indexing

In [54]:
arr[[0,2,4]] ##select any index

array([10, 30, 50])

### Boolean Masking

In [55]:
arr[arr>25]

array([30, 40, 50, 60])